### ISSUE TITLE
Crash with 3.14.1

### ISSUE THREAD

**Issue by AvangionQ** [blakkthunderr/Blakkmodd#9]
07:05:06.352 ERROR core.CardCrawlGame> Exception caught
java.lang.IllegalArgumentException: Animation not found: animation
	at com.esotericsoftware.spine.AnimationState.setAnimation(AnimationState.java:216) ~[?:?]
	at examplemod.characters.BlakkKnight.<init>(BlakkKnight.java:46) ~[BlakkMod.jar:?]
	at examplemod.ExampleMod.receiveEditCharacters(ExampleMod.java:104) ~[BlakkMod.jar:?]
	at basemod.BaseMod.publishEditCharacters(BaseMod.java:2387) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.EditCharactersHook.Insert(EditCharactersHook.java:20) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:289) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by AvangionQ** [comment]
Would you like a full log? https://filebin.net/xpmuuew148zfvyni/StS_crash_log.txt?t=bn6l5tgh
